# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scpt_gui_port_scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_PS(object):
    def setupUi(self, MainWindow_Pscan):
        MainWindow_Pscan.setObjectName("MainWindow")
        MainWindow_Pscan.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_Pscan.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_Pscan)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 771, 521))
        self.frame.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(430, 80, 88, 34))
        self.pushButton.setStyleSheet("alternate-background-color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(90, 220, 631, 281))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 80, 58, 18))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 70, 301, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 270, 58, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 20, 401, 18))
        self.label_3.setStyleSheet("color: rgb(255, 0, 255);\n"
"font: 20pt \"Noto Sans\";\n"
"font: 16pt \"Noto Sans\";")
        self.label_3.setObjectName("label_3")
        MainWindow_Pscan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_Pscan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuwindows = QtWidgets.QMenu(self.menubar)
        self.menuwindows.setObjectName("menuwindows")
        self.menupayload = QtWidgets.QMenu(self.menuwindows)
        self.menupayload.setObjectName("menupayload")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow_Pscan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Pscan)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Pscan.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow_Pscan)
        self.actionabout.setObjectName("actionabout")
        self.actionWEB = QtWidgets.QAction(MainWindow_Pscan)
        self.actionWEB.setObjectName("actionWEB")
        self.actionMITM = QtWidgets.QAction(MainWindow_Pscan)
        self.actionMITM.setObjectName("actionMITM")
        self.actioncryptography = QtWidgets.QAction(MainWindow_Pscan)
        self.actioncryptography.setObjectName("actioncryptography")
        self.actionBrute_force = QtWidgets.QAction(MainWindow_Pscan)
        self.actionBrute_force.setObjectName("actionBrute_force")
        self.actionPhishing = QtWidgets.QAction(MainWindow_Pscan)
        self.actionPhishing.setObjectName("actionPhishing")
        self.actionbtc_exploit = QtWidgets.QAction(MainWindow_Pscan)
        self.actionbtc_exploit.setObjectName("actionbtc_exploit")
        self.actiongoogle_dork = QtWidgets.QAction(MainWindow_Pscan)
        self.actiongoogle_dork.setObjectName("actiongoogle_dork")
        self.actionVulnerability_scan = QtWidgets.QAction(MainWindow_Pscan)
        self.actionVulnerability_scan.setObjectName("actionVulnerability_scan")
        self.actiongenerate_payload = QtWidgets.QAction(MainWindow_Pscan)
        self.actiongenerate_payload.setObjectName("actiongenerate_payload")
        self.actionbotnet = QtWidgets.QAction(MainWindow_Pscan)
        self.actionbotnet.setObjectName("actionbotnet")
        self.actionreverseShell = QtWidgets.QAction(MainWindow_Pscan)
        self.actionreverseShell.setObjectName("actionreverseShell")
        self.menupayload.addAction(self.actiongenerate_payload)
        self.menupayload.addAction(self.actionbotnet)
        self.menupayload.addAction(self.actionreverseShell)
        self.menuwindows.addAction(self.actionWEB)
        self.menuwindows.addAction(self.actionMITM)
        self.menuwindows.addAction(self.actioncryptography)
        self.menuwindows.addAction(self.menupayload.menuAction())
        self.menuwindows.addAction(self.actionBrute_force)
        self.menuwindows.addAction(self.actionPhishing)
        self.menuwindows.addAction(self.actionbtc_exploit)
        self.menuwindows.addAction(self.actiongoogle_dork)
        self.menuwindows.addAction(self.actionVulnerability_scan)
        self.menuhelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuwindows.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow_Pscan)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Pscan)

    def aboutss(self):
        from scpt_GUI_about import Ui_MainWindow_about
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_about()
        self.ui.setupUi(self.Form)
        # MainWindow_Pscan.close()
        self.Form.show()

    def websss(self, MainWindow_Pscan):
        from scpt_GUI_Web_scan import Ui_MainWindow_WS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_WS()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def mitmsss(self, MainWindow_Pscan):
        from scpt_GUI_MITM import Ui_MainWindow_Mitm
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Mitm()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def crptosss(self, MainWindow_Pscan):
        from scpt_GUI_cryptography import Ui_MainWindow_crypto
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_crypto()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Payload_G(self, MainWindow_Pscan):
        from scpt_GUI_generate_payload import Ui_MainWindow_GP
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GP()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Payload_Rev(self, MainWindow_Pscan):
        from scpt_GUI_Reverse_shell import Ui_MainWindow_RS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_RS()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Payload_bot(self, MainWindow_Pscan):
        from scpt_GUI_botnet import Ui_MainWindow_botnet
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_botnet()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Brutessss(self, MainWindow_Pscan):
        from scpt_GUI_brute_force import Ui_MainWindow_brute
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_brute()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Phisssss(self, MainWindow_Pscan):
        from scpt_GUI_Phishing import Ui_MainWindow_Ph
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Ph()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def BTC_esss(self, MainWindow_Pscan):
        from scpt_GUI_btc_exploit import Ui_MainWindow_btc
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_btc()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def Googlesss(self, MainWindow_Pscan):
        from scpt_GUI_Google_Dork import Ui_MainWindow_GD
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GD()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()



    def vunlssss(self, MainWindow_Pscan):
        from scpt_GUI_vulnerability_search import Ui_MainWindow_VS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_VS()
        self.ui.setupUi(self.Form)
        MainWindow_Pscan.close()
        self.Form.show()

    def retranslateUi(self, MainWindow_Pscan):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Pscan.setWindowTitle(_translate("MainWindow", "SCPT-Port-scan"))
        self.pushButton.setText(_translate("MainWindow", "sub"))
        self.label.setText(_translate("MainWindow", "target_ip:"))
        self.label_2.setText(_translate("MainWindow", "output:"))
        self.label_3.setText(_translate("MainWindow", "if you have many tergets sbertthem by , "))
        self.menuwindows.setTitle(_translate("MainWindow", "windows"))
        self.menupayload.setTitle(_translate("MainWindow", "payload"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionWEB.setText(_translate("MainWindow", "WEB"))
        self.actionMITM.setText(_translate("MainWindow", "MITM"))
        self.actioncryptography.setText(_translate("MainWindow", "cryptography"))
        self.actionBrute_force.setText(_translate("MainWindow", "Brute-force"))
        self.actionPhishing.setText(_translate("MainWindow", "Phishing"))
        self.actionbtc_exploit.setText(_translate("MainWindow", "btc-exploit"))
        self.actiongoogle_dork.setText(_translate("MainWindow", "google-dork"))
        self.actionVulnerability_scan.setText(_translate("MainWindow", "Vulnerability-scan"))
        self.actiongenerate_payload.setText(_translate("MainWindow", "generate-payload"))
        self.actionbotnet.setText(_translate("MainWindow", "botnet"))
        self.actionreverseShell.setText(_translate("MainWindow", "reverseShell"))

        self.actionWEB.triggered.connect(lambda:self.websss(MainWindow_Pscan))
        self.actionMITM.triggered.connect(lambda:self.mitmsss(MainWindow_Pscan))
        self.actioncryptography.triggered.connect(lambda:self.crptosss(MainWindow_Pscan))
        self.actionBrute_force.triggered.connect(lambda:self.Brutessss(MainWindow_Pscan))
        self.actionPhishing.triggered.connect(lambda:self.Phisssss(MainWindow_Pscan))
        self.actiongenerate_payload.triggered.connect(lambda:self.Payload_G(MainWindow_Pscan))
        self.actionreverseShell.triggered.connect(lambda:self.Payload_Rev(MainWindow_Pscan))
        self.actionbotnet.triggered.connect(lambda:self.Payload_bot(MainWindow_Pscan))
        self.actionbtc_exploit.triggered.connect(lambda:self.BTC_esss(MainWindow_Pscan))
        self.actiongoogle_dork.triggered.connect(lambda:self.Googlesss(MainWindow_Pscan))
        self.actionVulnerability_scan.triggered.connect(lambda:self.vunlssss(MainWindow_Pscan))
        self.actionabout.triggered.connect(self.aboutss)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Pscan = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_PS()
    ui.setupUi(MainWindow_Pscan)
    MainWindow_Pscan.show()
    sys.exit(app.exec_())
