# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scpt_gui_generate_payload.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_GP(object):
    def setupUi(self, MainWindow_GP):
        MainWindow_GP.setObjectName("MainWindow")
        MainWindow_GP.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_GP.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_GP)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 110, 58, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 58, 18))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(130, 30, 101, 41))
        self.comboBox.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 340, 101, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(90, 100, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 210, 321, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 330, 301, 51))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(450, 340, 88, 34))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 101, 18))
        self.label_4.setObjectName("label_4")
        MainWindow_GP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_GP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuwindows = QtWidgets.QMenu(self.menubar)
        self.menuwindows.setObjectName("menuwindows")
        self.menupayload = QtWidgets.QMenu(self.menuwindows)
        self.menupayload.setObjectName("menupayload")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow_GP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_GP)
        self.statusbar.setObjectName("statusbar")
        MainWindow_GP.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow_GP)
        self.actionabout.setObjectName("actionabout")
        self.actionWEB = QtWidgets.QAction(MainWindow_GP)
        self.actionWEB.setObjectName("actionWEB")
        self.actionMITM = QtWidgets.QAction(MainWindow_GP)
        self.actionMITM.setObjectName("actionMITM")
        self.actioncryptography = QtWidgets.QAction(MainWindow_GP)
        self.actioncryptography.setObjectName("actioncryptography")
        self.actionreverseShell = QtWidgets.QAction(MainWindow_GP)
        self.actionreverseShell.setObjectName("actionreverseShell")
        self.actionbotnet = QtWidgets.QAction(MainWindow_GP)
        self.actionbotnet.setObjectName("actionbotnet")
        self.actionBrute_force = QtWidgets.QAction(MainWindow_GP)
        self.actionBrute_force.setObjectName("actionBrute_force")
        self.actionPhishing = QtWidgets.QAction(MainWindow_GP)
        self.actionPhishing.setObjectName("actionPhishing")
        self.actionbtc_exploit = QtWidgets.QAction(MainWindow_GP)
        self.actionbtc_exploit.setObjectName("actionbtc_exploit")
        self.actiongoogle_dork = QtWidgets.QAction(MainWindow_GP)
        self.actiongoogle_dork.setObjectName("actiongoogle_dork")
        self.actionport_scan = QtWidgets.QAction(MainWindow_GP)
        self.actionport_scan.setObjectName("actionport_scan")
        self.actionVulnerability_scan = QtWidgets.QAction(MainWindow_GP)
        self.actionVulnerability_scan.setObjectName("actionVulnerability_scan")
        self.menupayload.addAction(self.actionreverseShell)
        self.menupayload.addAction(self.actionbotnet)
        self.menuwindows.addAction(self.actionWEB)
        self.menuwindows.addAction(self.actionMITM)
        self.menuwindows.addAction(self.actioncryptography)
        self.menuwindows.addAction(self.menupayload.menuAction())
        self.menuwindows.addAction(self.actionBrute_force)
        self.menuwindows.addAction(self.actionPhishing)
        self.menuwindows.addAction(self.actionbtc_exploit)
        self.menuwindows.addAction(self.actiongoogle_dork)
        self.menuwindows.addAction(self.actionport_scan)
        self.menuwindows.addAction(self.actionVulnerability_scan)
        self.menuHelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuwindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow_GP)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_GP)

    def aboutss(self):
        from scpt_GUI_about import Ui_MainWindow_about
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_about()
        self.ui.setupUi(self.Form)
        # MainWindow_GP.close()
        self.Form.show()

    def websss(self, MainWindow_GP):
        from scpt_GUI_Web_scan import Ui_MainWindow_WS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_WS()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def mitmsss(self, MainWindow_GP):
        from scpt_GUI_MITM import Ui_MainWindow_Mitm
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Mitm()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def crptosss(self, MainWindow_GP):
        from scpt_GUI_cryptography import Ui_MainWindow_crypto
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_crypto()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()



    def Payload_Rev(self, MainWindow_GP):
        from scpt_GUI_Reverse_shell import Ui_MainWindow_RS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_RS()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def Payload_bot(self, MainWindow_GP):
        from scpt_GUI_botnet import Ui_MainWindow_botnet
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_botnet()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def Brutessss(self, MainWindow_GP):
        from scpt_GUI_brute_force import Ui_MainWindow_brute
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_brute()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def Phisssss(self, MainWindow_GP):
        from scpt_GUI_Phishing import Ui_MainWindow_Ph
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Ph()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def BTC_esss(self, MainWindow_GP):
        from scpt_GUI_btc_exploit import Ui_MainWindow_btc
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_btc()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def Googlesss(self, MainWindow_GP):
        from scpt_GUI_Google_Dork import Ui_MainWindow_GD
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GD()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def Port_scansss(self, MainWindow_GP):
        from scpt_GUI_Port_scan import Ui_MainWindow_PS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_PS()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def vunlssss(self, MainWindow_GP):
        from scpt_GUI_vulnerability_search import Ui_MainWindow_VS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_VS()
        self.ui.setupUi(self.Form)
        MainWindow_GP.close()
        self.Form.show()

    def retranslateUi(self, MainWindow_GP):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_GP.setWindowTitle(_translate("MainWindow", "SCPT-Generate-Payload"))
        self.label.setText(_translate("MainWindow", "Host:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "IP"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Host"))
        self.label_3.setText(_translate("MainWindow", "Payload Name:"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.label_4.setText(_translate("MainWindow", "Type of  payload:"))
        self.menuwindows.setTitle(_translate("MainWindow", "windows"))
        self.menupayload.setTitle(_translate("MainWindow", "payload"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionWEB.setText(_translate("MainWindow", "WEB"))
        self.actionMITM.setText(_translate("MainWindow", "MITM"))
        self.actioncryptography.setText(_translate("MainWindow", "cryptography"))
        self.actionreverseShell.setText(_translate("MainWindow", "reverseShell"))
        self.actionbotnet.setText(_translate("MainWindow", "botnet"))
        self.actionBrute_force.setText(_translate("MainWindow", "Brute-force"))
        self.actionPhishing.setText(_translate("MainWindow", "Phishing"))
        self.actionbtc_exploit.setText(_translate("MainWindow", "btc-exploit"))
        self.actiongoogle_dork.setText(_translate("MainWindow", "google-dork"))
        self.actionport_scan.setText(_translate("MainWindow", "port-scan"))
        self.actionVulnerability_scan.setText(_translate("MainWindow", "Vulnerability-scan"))

        self.actionWEB.triggered.connect(lambda:self.websss(MainWindow_GP))
        self.actionMITM.triggered.connect(lambda:self.mitmsss(MainWindow_GP))
        self.actioncryptography.triggered.connect(lambda:self.crptosss(MainWindow_GP))
        self.actionBrute_force.triggered.connect(lambda:self.Brutessss(MainWindow_GP))
        self.actionPhishing.triggered.connect(lambda:self.Phisssss(MainWindow_GP))
        self.actionreverseShell.triggered.connect(lambda:self.Payload_Rev(MainWindow_GP))
        self.actionbtc_exploit.triggered.connect(lambda:self.BTC_esss(MainWindow_GP))
        self.actiongoogle_dork.triggered.connect(lambda:self.Googlesss(MainWindow_GP))
        self.actionport_scan.triggered.connect(lambda:self.Port_scansss(MainWindow_GP))
        self.actionVulnerability_scan.triggered.connect(lambda:self.vunlssss(MainWindow_GP))
        self.actionabout.triggered.connect(self.aboutss)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_GP = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_GP()
    ui.setupUi(MainWindow_GP)
    MainWindow_GP.show()
    sys.exit(app.exec_())
