# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCPT_gui_Brute_force.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_brute(object):
    def setupUi(self, MainWindow_brute):
        MainWindow_brute.setObjectName("MainWindow")
        MainWindow_brute.resize(964, 693)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_brute.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_brute)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 10, 131, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 70, 441, 561))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 160, 58, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 58, 18))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(80, 40, 141, 31))
        self.comboBox.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 58, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 58, 18))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 160, 231, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 100, 231, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(70, 200, 341, 341))
        self.textEdit.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 160, 88, 34))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 100, 88, 34))
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(450, 70, 481, 571))
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 90, 88, 34))
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 58, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 90, 261, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 150, 381, 411))
        self.textEdit_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 58, 18))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 131, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow_brute.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_brute)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 30))
        self.menubar.setObjectName("menubar")
        self.menuwindows = QtWidgets.QMenu(self.menubar)
        self.menuwindows.setObjectName("menuwindows")
        self.menupayload = QtWidgets.QMenu(self.menuwindows)
        self.menupayload.setObjectName("menupayload")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow_brute.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_brute)
        self.statusbar.setObjectName("statusbar")
        MainWindow_brute.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow_brute)
        self.actionabout.setObjectName("actionabout")
        self.actionWEB = QtWidgets.QAction(MainWindow_brute)
        self.actionWEB.setObjectName("actionWEB")
        self.actionMITM = QtWidgets.QAction(MainWindow_brute)
        self.actionMITM.setObjectName("actionMITM")
        self.actioncryptography = QtWidgets.QAction(MainWindow_brute)
        self.actioncryptography.setObjectName("actioncryptography")
        self.actiongenerate_payload = QtWidgets.QAction(MainWindow_brute)
        self.actiongenerate_payload.setObjectName("actiongenerate_payload")
        self.actionreverseShell = QtWidgets.QAction(MainWindow_brute)
        self.actionreverseShell.setObjectName("actionreverseShell")
        self.actionbotnet = QtWidgets.QAction(MainWindow_brute)
        self.actionbotnet.setObjectName("actionbotnet")
        self.actionPhishing = QtWidgets.QAction(MainWindow_brute)
        self.actionPhishing.setObjectName("actionPhishing")
        self.actionbtc_exploit = QtWidgets.QAction(MainWindow_brute)
        self.actionbtc_exploit.setObjectName("actionbtc_exploit")
        self.actiongoogle_dork = QtWidgets.QAction(MainWindow_brute)
        self.actiongoogle_dork.setObjectName("actiongoogle_dork")
        self.actionport_scan = QtWidgets.QAction(MainWindow_brute)
        self.actionport_scan.setObjectName("actionport_scan")
        self.actionVulnerability_scan = QtWidgets.QAction(MainWindow_brute)
        self.actionVulnerability_scan.setObjectName("actionVulnerability_scan")
        self.menupayload.addAction(self.actiongenerate_payload)
        self.menupayload.addAction(self.actionreverseShell)
        self.menupayload.addAction(self.actionbotnet)
        self.menuwindows.addAction(self.actionWEB)
        self.menuwindows.addAction(self.actionMITM)
        self.menuwindows.addAction(self.actioncryptography)
        self.menuwindows.addAction(self.menupayload.menuAction())
        self.menuwindows.addAction(self.actionPhishing)
        self.menuwindows.addAction(self.actionbtc_exploit)
        self.menuwindows.addAction(self.actiongoogle_dork)
        self.menuwindows.addAction(self.actionport_scan)
        self.menuwindows.addAction(self.actionVulnerability_scan)
        self.menuhelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuwindows.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.frame_2.hide()
        self.frame.hide()

        self.retranslateUi(MainWindow_brute)
        self.pushButton.clicked.connect(self.frame.show)
        self.pushButton.clicked.connect(self.frame_2.hide)
        self.pushButton_2.clicked.connect(self.frame.hide)
        self.pushButton_2.clicked.connect(self.frame_2.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_brute)

    def aboutss(self):
        from scpt_GUI_about import Ui_MainWindow_about
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_about()
        self.ui.setupUi(self.Form)
        # MainWindow_brute.close()
        self.Form.show()

    def websss(self, MainWindow_brute):
        from scpt_GUI_Web_scan import Ui_MainWindow_WS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_WS()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def mitmsss(self, MainWindow_brute):
        from scpt_GUI_MITM import Ui_MainWindow_Mitm
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Mitm()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def crptosss(self, MainWindow_brute):
        from scpt_GUI_cryptography import Ui_MainWindow_crypto
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_crypto()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def Payload_G(self, MainWindow_brute):
        from scpt_GUI_generate_payload import Ui_MainWindow_GP
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GP()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def Payload_Rev(self, MainWindow_brute):
        from scpt_GUI_Reverse_shell import Ui_MainWindow_RS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_RS()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def Payload_bot(self, MainWindow_brute):
        from scpt_GUI_botnet import Ui_MainWindow_botnet
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_botnet()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()



    def Phisssss(self, MainWindow_brute):
        from scpt_GUI_Phishing import Ui_MainWindow_Ph
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Ph()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def BTC_esss(self, MainWindow_brute):
        from scpt_GUI_btc_exploit import Ui_MainWindow_btc
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_btc()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def Googlesss(self, MainWindow_brute):
        from scpt_GUI_Google_Dork import Ui_MainWindow_GD
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GD()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def Port_scansss(self, MainWindow_brute):
        from scpt_GUI_Port_scan import Ui_MainWindow_PS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_PS()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def vunlssss(self, MainWindow_brute):
        from scpt_GUI_vulnerability_search import Ui_MainWindow_VS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_VS()
        self.ui.setupUi(self.Form)
        MainWindow_brute.close()
        self.Form.show()

    def retranslateUi(self, MainWindow_brute):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_brute.setWindowTitle(_translate("MainWindow", "SCPT-Brute-force"))
        self.pushButton.setText(_translate("MainWindow", "service"))
        self.pushButton_2.setText(_translate("MainWindow", "Cryptocurrency"))
        self.label.setText(_translate("MainWindow", "target:"))
        self.label_2.setText(_translate("MainWindow", "output:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ssh"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ftb"))
        self.label_3.setText(_translate("MainWindow", "service:"))
        self.label_4.setText(_translate("MainWindow", "wordlist:"))
        self.pushButton_4.setText(_translate("MainWindow", "run"))
        self.pushButton_5.setText(_translate("MainWindow", "browse"))
        self.pushButton_6.setText(_translate("MainWindow", "run"))
        self.label_5.setText(_translate("MainWindow", "output:"))
        self.label_6.setText(_translate("MainWindow", "target_address:"))
        self.label_7.setText(_translate("MainWindow", "currency:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "btc"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "ETH"))
        self.menuwindows.setTitle(_translate("MainWindow", "windows"))
        self.menupayload.setTitle(_translate("MainWindow", "payload"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionWEB.setText(_translate("MainWindow", "WEB"))
        self.actionMITM.setText(_translate("MainWindow", "MITM"))
        self.actioncryptography.setText(_translate("MainWindow", "cryptography"))
        self.actiongenerate_payload.setText(_translate("MainWindow", "generate-payload"))
        self.actionreverseShell.setText(_translate("MainWindow", "reverseShell"))
        self.actionbotnet.setText(_translate("MainWindow", "botnet"))
        self.actionPhishing.setText(_translate("MainWindow", "Phishing"))
        self.actionbtc_exploit.setText(_translate("MainWindow", "btc-exploit"))
        self.actiongoogle_dork.setText(_translate("MainWindow", "google-dork"))
        self.actionport_scan.setText(_translate("MainWindow", "port-scan"))
        self.actionVulnerability_scan.setText(_translate("MainWindow", "Vulnerability-scan"))

        self.actionWEB.triggered.connect(lambda:self.websss(MainWindow_brute))
        self.actionMITM.triggered.connect(lambda:self.mitmsss(MainWindow_brute))
        self.actioncryptography.triggered.connect(lambda:self.crptosss(MainWindow_brute))
        self.actionPhishing.triggered.connect(lambda:self.Phisssss(MainWindow_brute))
        self.actiongenerate_payload.triggered.connect(lambda:self.Payload_G(MainWindow_brute))
        self.actionreverseShell.triggered.connect(lambda:self.Payload_Rev(MainWindow_brute))
        self.actionbotnet.triggered.connect(lambda:self.Payload_bot(MainWindow_brute))
        self.actionbtc_exploit.triggered.connect(lambda:self.BTC_esss(MainWindow_brute))
        self.actiongoogle_dork.triggered.connect(lambda:self.Googlesss(MainWindow_brute))
        self.actionport_scan.triggered.connect(lambda:self.Port_scansss(MainWindow_brute))
        self.actionVulnerability_scan.triggered.connect(lambda:self.vunlssss(MainWindow_brute))
        self.actionabout.triggered.connect(self.aboutss)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_brute = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_brute()
    ui.setupUi(MainWindow_brute)
    MainWindow_brute.show()
    sys.exit(app.exec_())
