# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scpt_gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 180, 491, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuwindows = QtWidgets.QMenu(self.menubar)
        self.menuwindows.setObjectName("menuwindows")
        self.menupayload = QtWidgets.QMenu(self.menuwindows)
        self.menupayload.setObjectName("menupayload")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionweb = QtWidgets.QAction(MainWindow)
        self.actionweb.setObjectName("actionweb")
        self.actionmint = QtWidgets.QAction(MainWindow)
        self.actionmint.setObjectName("actionmint")
        self.actioncrypto = QtWidgets.QAction(MainWindow)
        self.actioncrypto.setObjectName("actioncrypto")
        self.actionBrute_force = QtWidgets.QAction(MainWindow)
        self.actionBrute_force.setObjectName("actionBrute_force")
        self.actionPhishing = QtWidgets.QAction(MainWindow)
        self.actionPhishing.setObjectName("actionPhishing")
        self.actiongenerate_payload = QtWidgets.QAction(MainWindow)
        self.actiongenerate_payload.setObjectName("actiongenerate_payload")
        self.actionbotnet = QtWidgets.QAction(MainWindow)
        self.actionbotnet.setObjectName("actionbotnet")
        self.actionreverse_shell = QtWidgets.QAction(MainWindow)
        self.actionreverse_shell.setObjectName("actionreverse_shell")
        self.actionbtc_exploit = QtWidgets.QAction(MainWindow)
        self.actionbtc_exploit.setObjectName("actionbtc_exploit")
        self.actiongoogle_dork = QtWidgets.QAction(MainWindow)
        self.actiongoogle_dork.setObjectName("actiongoogle_dork")
        self.actionport_scan = QtWidgets.QAction(MainWindow)
        self.actionport_scan.setObjectName("actionport_scan")
        self.actionVulnerability_scan = QtWidgets.QAction(MainWindow)
        self.actionVulnerability_scan.setObjectName("actionVulnerability_scan")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menupayload.addAction(self.actiongenerate_payload)
        self.menupayload.addAction(self.actionbotnet)
        self.menupayload.addAction(self.actionreverse_shell)
        self.menuwindows.addAction(self.actionweb)
        self.menuwindows.addAction(self.actionmint)
        self.menuwindows.addAction(self.actioncrypto)
        self.menuwindows.addAction(self.menupayload.menuAction())
        self.menuwindows.addAction(self.actionBrute_force)
        self.menuwindows.addAction(self.actionPhishing)
        self.menuwindows.addAction(self.actionbtc_exploit)
        self.menuwindows.addAction(self.actiongoogle_dork)
        self.menuwindows.addAction(self.actionport_scan)
        self.menuwindows.addAction(self.actionVulnerability_scan)
        self.menuhelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuwindows.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def aboutss(self):
        from scpt_GUI_about import Ui_MainWindow_about
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_about()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()
    def websss(self):
        from scpt_GUI_Web_scan import Ui_MainWindow_WS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_WS()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def mitmsss(self):
        from scpt_GUI_MITM import Ui_MainWindow_Mitm
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Mitm()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def crptosss(self):
        from scpt_GUI_cryptography import Ui_MainWindow_crypto
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_crypto()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Payload_G(self):
        from scpt_GUI_generate_payload import Ui_MainWindow_GP
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GP()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Payload_Rev(self):
        from scpt_GUI_Reverse_shell import Ui_MainWindow_RS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_RS()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Payload_bot(self):
        from scpt_GUI_botnet import Ui_MainWindow_botnet
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_botnet()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Brutessss(self):
        from scpt_GUI_brute_force import Ui_MainWindow_brute
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_brute()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Phisssss(self):
        from scpt_GUI_Phishing import Ui_MainWindow_Ph
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Ph()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def BTC_esss(self):
        from scpt_GUI_btc_exploit import Ui_MainWindow_btc
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_btc()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def Googlesss(self):
        from scpt_GUI_Google_Dork import Ui_MainWindow_GD
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_GD()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()

    def Port_scansss(self):
        from scpt_GUI_Port_scan import Ui_MainWindow_PS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_PS()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()
    def vunlssss(self):
        from scpt_GUI_vulnerability_search import Ui_MainWindow_VS
        # code the 2nd screen here
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_VS()
        self.ui.setupUi(self.Form)
        MainWindow.close()
        self.Form.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCPT"))
        self.label.setText(_translate("MainWindow", "welcome to SCPT"))
        self.menuwindows.setTitle(_translate("MainWindow", "windows"))
        self.menupayload.setTitle(_translate("MainWindow", "payload"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionweb.setText(_translate("MainWindow", "web"))
        self.actionweb.triggered.connect(self.websss)
        # self.actionweb.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionmint.setText(_translate("MainWindow", "MITM"))
        self.actionmint.triggered.connect(self.mitmsss)
        # self.actionmint.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actioncrypto.setText(_translate("MainWindow", "cryptography"))
        self.actioncrypto.triggered.connect(self.crptosss)
        # self.actioncrypto.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionBrute_force.setText(_translate("MainWindow", "Brute-force"))
        self.actionBrute_force.triggered.connect(self.Brutessss)
        self.actionPhishing.setText(_translate("MainWindow", "Phishing"))
        self.actionPhishing.triggered.connect(self.Phisssss)
        self.actiongenerate_payload.setText(_translate("MainWindow", "generate-payload"))
        self.actiongenerate_payload.triggered.connect(self.Payload_G)
        self.actionbotnet.setText(_translate("MainWindow", "botnet"))
        self.actionbotnet.triggered.connect(self.Payload_bot)
        self.actionreverse_shell.setText(_translate("MainWindow", "reverse-shell"))
        self.actionreverse_shell.triggered.connect(self.Payload_Rev)
        self.actionbtc_exploit.setText(_translate("MainWindow", "btc-exploit"))
        self.actionbtc_exploit.triggered.connect(self.BTC_esss)
        self.actiongoogle_dork.setText(_translate("MainWindow", "google-dork"))
        self.actiongoogle_dork.triggered.connect(self.Googlesss)
        self.actionport_scan.setText(_translate("MainWindow", "port-scan"))
        self.actionport_scan.triggered.connect(self.Port_scansss)
        self.actionVulnerability_scan.setText(_translate("MainWindow", "Vulnerability-scan"))
        self.actionVulnerability_scan.triggered.connect(self.vunlssss)
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionabout.triggered.connect(self.aboutss)

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
def mainG():


    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    mainG()
